oxidecomputer/quartz

- hdl/projects/sidecar/mainboard/TofinoDebugPort.bsv
- hdl/projects/sidecar/mainboard/test/BUILD
- hdl/projects/sidecar/mainboard/test/TofinoDebugPortTests.bsv
#210 missed TofinoDebugPortTest. This diff refactors the tests to use the I2CTestParam struct for initialization and reflect the fact that the controller will ack poll.
> Fix TofinoDebugPortTest

- hdl/ip/vhd/vunit_components/BUCK
- hdl/ip/vhd/vunit_components/basic_stream/basic_sink.vhd
- hdl/ip/vhd/vunit_components/basic_stream/basic_source.vhd
- hdl/ip/vhd/vunit_components/basic_stream/basic_stream_pkg.vhd
- hdl/ip/vhd/vunit_components/basic_stream/sims/tb_basic_stream.vhd
- hdl/ip/vhd/vunit_components/basic_stream/sims/th_basic_stream.vhd
This adds basic stream verification components. The basic stream source/sink occupy a middle ground with VUnit's stream master/slave being simpler (just push/pop of data) and VUnit's AXI/Avalon being richer (more framing and control options). These components allow for pushing and popping of data while respecting the source's `valid` and the sink's `ready`.
> Add basic stream VCs

- hdl/ip/vhd/synchronizers/bacd.vhd
- hdl/ip/vhd/synchronizers/sims/synchronizers_th.vhd
- hdl/ip/vhd/synchronizers/tacd.vhd
- hdl/ip/vhd/uart/sims/uart_th.vhd
This was a hold-over from me trying to be clever and not use async resets for some of these blocks.  I'm generally convinced doing this isn't worth the hassle and lack of clarity.  I found at least one bug or unexpected behavior where when the design comes out of reset but on of the lines here was held high we'd miss the handshake.  Adding back in the various domain resets to tacd resolves that issue with no real functionality change but the interface changes slightly to accommodate the additional resets.
Also fixed uart testbench which was missed on a previous change.
> Update synchronizers to use resets, fix broken uart tb

- hdl/ip/vhd/common/utils/time_pkg.vhd
When we actually construct the return value in [`private_internal_calc`](https://github.com/oxidecomputer/quartz/blob/main/hdl/ip/vhd/common/utils/time_pkg.vhd#L149), anything less than the size of VHDL's `INTEGER` type of 32-bits yields a vector truncation warning since we're trimming down a `NATURAL` (an `INTEGER` between 0 and 2^31).
```vhdl
constant TEST : unsigned(7 downto 0) := calc_ns(SOME_TEST_NS, CLK_PER_NS, 8);
```
```
** Warning: NUMERIC_STD.TO_UNSIGNED: vector truncated
...
Function TO_UNSIGNED [NATURAL, NATURAL return UNRESOLVED_UNSIGNED] at ../lib/ieee.08/numeric_std-body.vhdl:3078
Function PRIVATE_INTERNAL_CALC [POSITIVE, POSITIVE, POSITIVE, POSITIVE return UNSIGNED] at /home/aaron/Oxide/git/quartz/hdl/ip/vhd/common/utils/time_pkg.vhd:149
Function CALC_NS [POSITIVE, …
```
> Adjust time_pkg::private_internal_calc to remove truncation warning

- .github/workflows/build.yml
- hdl/ip/vhd/espi/sys_regs/espi_regs.rdl
- hdl/ip/vhd/info/BUCK
- hdl/ip/vhd/info/info.vhd
- hdl/ip/vhd/info/info_2k8.vhd
- hdl/ip/vhd/info/info_regs.rdl
- hdl/projects/grapefruit/BUCK
- hdl/projects/grapefruit/grapefruit_top.vhd
- toolchains/BUCK
- tools/vhdl-ls.bxl
One minor spelling fix and I noticed a bug in the bsv change detector that was running on buck2-based changes.
But the real feature: git-sha generated into a register block.
This is possibly a bit of a janky implementation but I think it meets our needs for now:
We're using a "genrule" defined in the BUCK file to run a minor bit of shell to generate a simple VHDL package with the short-sha in there.  We then use this as a dependency and build out a simple register block that covers the identity, git-sha, scratchpad and checksum registers I expect will be common on most of our designs.
I implemented the business portion of this in the info_2k8.vhd folder which doesn't use VHDL interfaces (a 2k19 feature) and then built a 2k19-compatible wrapper around that so we can use in both the Xilinx …
> Git SHA gen and common info block

- tools/hdl.bzl
- tools/multitool/multitool_cli.py
that are stripped from synth but keep the LSP happy.  This is currently targetted at generated IP for which we have no entity until synthesis runs.
This allows us to make empty ones and depend on them in the tree, but not export them for synthesis and/or simulation.
Also remove an extraneous print.
> Add support for "black-box" (ie no-implementation) entities

- hdl/ip/bsv/I2C/I2CBitController.bsv
- hdl/ip/bsv/I2C/I2CCore.bsv
- hdl/ip/bsv/I2C/test/I2CBitControllerTests.bsv
- hdl/ip/bsv/I2C/test/I2CCoreTests.bsv
- hdl/ip/bsv/I2C/test/I2CPeripheralModel.bsv
- hdl/projects/sidecar/qsfp_x32/QSFPModule/test/QsfpModuleControllerTests.bsv
- hdl/projects/sidecar/qsfp_x32/QSFPModule/test/QsfpModuleControllerTests.gtkw
This commit fixes a couple of bugs related to SCL stretching. First off, in the `I2CBitController` I adjusted how we sample SCL to detect stretching so we're not errantly sampling. Then in the `I2CCore` I added a mechanism to handle the SCL stretch timeouts when we see them. Before we lacked this and that meant if that was seen, we were wedged. The rest of the changes were to test cases in order to mimic the behavior observed that brought the problems to our attention.
Fixes #246
Fixes #247
> I2C: A couple of fixes around SCL stretching is handled

- hdl/ip/vhd/vunit_components/basic_stream/basic_sink.vhd
- hdl/ip/vhd/vunit_components/basic_stream/sims/th_basic_stream.vhd
We should only `exit` in the message receive loop once we've sampled `valid` data. Currently it was leaving the message receive loop once `ready` was asserted, regardless if `valid` was too, leaving the message not replied to!
> basic-sink: fix message receive loop exit

- hdl/ip/vhd/common/BUCK
- hdl/ip/vhd/common/countdown/countdown.vhd
- hdl/ip/vhd/common/countdown/sims/countdown_tb.gtkw
- hdl/ip/vhd/common/countdown/sims/countdown_tb.vhd
- hdl/ip/vhd/common/countdown/sims/countdown_th.vhd
- hdl/ip/vhd/common/strobe/sims/strobe_tb.vhd
- hdl/ip/vhd/common/strobe/sims/strobe_th.vhd
- hdl/ip/vhd/common/strobe/strobe.vhd
Also shuffle around a few things in the common BUCK file to make it alphabetical order.
> Add a countdown module and make strobe VHDL2008 compliant

- hdl/ip/vhd/espi/espi_target_top.vhd
- hdl/ip/vhd/espi/link_layer/cmd_sizer.vhd
- hdl/ip/vhd/espi/link_layer/link_layer_pkg.vhd
- hdl/ip/vhd/espi/peripheral_channel/uart_channel_top.vhd
- hdl/ip/vhd/espi/sims/espi_tb.vhd
- hdl/ip/vhd/espi/sims/espi_tb_pkg.vhd
- hdl/ip/vhd/espi/sims/models/espi_controller_vc_pkg.vhd
- hdl/ip/vhd/espi/sims/models/espi_dbg_vc_pkg.vhd
- hdl/ip/vhd/espi/txn_layer/command_processor.vhd
- hdl/ip/vhd/espi/txn_layer/espi_base_types_pkg.vhd
- hdl/ip/vhd/espi/txn_layer/espi_protocol_pkg.vhd
- hdl/ip/vhd/espi/txn_layer/response_processor.vhd
- hdl/ip/vhd/espi/txn_layer/txn_layer_top.vhd
We have the OOB message path basically working with the SP5, so we're going to plumb this all up a little more formally.
I had most of this in place before, but it was kind of hacked in and didn't have test coverage (and also not right in some places!) So this adds this path, as the enabled default and includes a test case that shoots UART data through.
This is still pending a tiny bit of testing on hw but assuming that goes well I'll merge this in.
> Wire back up OOB as our path of choice for now

- hdl/ip/vhd/espi/espi_spec_regs.vhd
- hdl/ip/vhd/espi/sys_regs/espi_regs.vhd
- tools/vivado_gen/templates/synth.jinja2
Fixes a few compile warnings  and a few other comment-like changes I had hanging around. No real functional changes here, we just hint to vivado to find the xpm stuff so it doesn't complain about the fact that it found them without a hint :)
> Warning cleanup

- tools/site_cobble/rdl_pkg/listeners.py
- tools/site_cobble/rdl_pkg/models.py
- tools/site_cobble/rdl_pkg/templates/regpkg_vhdl.jinja2
We had various deficiencies around sharing and overriding reset values on registers that share types. This provides the groundwork for better functioning here and provides error messages when the user asks for something we don't support. We also added new reset_0s and reset_1s functions to all register types so long as they don't have enumerated types. This provides some additional easy knobs to get alternate reset values for your register types.
This isn't at totally generic, full solve but provides some additional tools like the reset_1s, reset_0s functions and at least error messages when things are done that aren't supported currently vs silently doing the unexpected/wrong thing.  We will also elide generating the rec_reset function if a reset value was not set for a given register …
> Fix various deficiencies around type sharing and types with conflicting reset overrides.

- hdl/ip/vhd/vunit_components/BUCK
- hdl/ip/vhd/vunit_components/qspi_controller/qspi_vc_pkg.vhd
- hdl/ip/vhd/vunit_components/spi_controller/README.md
- hdl/ip/vhd/vunit_components/spi_controller/spi_master.vhd
- hdl/ip/vhd/vunit_components/spi_controller/spi_pkg.vhd
- hdl/ip/vhd/vunit_components/spi_controller/spi_slave.vhd
- tools/hdl.bzl
- tools/multitool/multitool_cli.py
- tools/vunit_gen/templates/run_py.jinja2
This pulls in some code that hasn't yet made it upstream in VUnit due to some discussion over there around re-structuring VCs etc. I'd rather just use this than write new so I'm vendoring it here for now and we can dump it later should this, or something similar merge upstream.
In doing this, I noticed a gap in our lsp-toml process, we can specify any library for sources added but were blindly replacing the libraries "vunit_lib" and "osvvm" with the files we found locally.  We actually want to concatenate any user-specified files and the automatically found ones when generating the lsp-toml, so that is now done for both of these libraries.
I also added a few transparent updates to the qspi-vc to better align with my understanding of the eventual VUnit VC spec, but it's still not fully …
> Vendor spi vc which is languishing in a PR over in VUnit

- .github/cleanup.sh
- .github/workflows/build.yml
- .github/workflows/simulation.yml
- hdl/projects/grapefruit/BUCK
- tools/compress.bzl
- tools/site_cobble/rdl_pkg/json_dump.py
- tools/site_cobble/rdl_pkg/rdl_cli.py
- tools/vivado.bzl
- tools/yosys.bzl
3 changes here:
Firstly, we're going to compress the ice40 bitstreams also. I factored out the compression logic into its own spot so that it can be shared from one place between the vivado and ice40 flows.  Fixes #276 
Secondly, chatting with @mkeeter, we wanted to also spit out a top-level json file as part of the build that has the appropriate offsets mapped so that hubris can better code-gen drivers etc, so this is done here also when we ask for a top-level .json output in our top-level BUCK files.
And finally, added a post-job cleanup action so we stop filling the build machine disk.  Fixes #267
top level json generates output that looks like this for reference. We're already generating the individual .json files for each peripheral just without the fully-elaborated address_offset …
> Build improvements for better hubris integration.

- hdl/ip/vhd/i2c/common/sims/i2c_cmd_vc.vhd
- hdl/ip/vhd/i2c/common/sims/i2c_cmd_vc_pkg.vhd
- hdl/ip/vhd/i2c/common/sims/i2c_target_vc.vhd
- hdl/ip/vhd/i2c/common/sims/i2c_target_vc_pkg.vhd
- hdl/ip/vhd/i2c/controller/link_layer/i2c_ctrl_link_layer.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/i2c_ctrl_txn_layer.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_tb.gtkw
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_tb.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_th.vhd
A feature we need for the SPD mux testing is the ability for our controller to abort an in-progress transaction. This commit adds an `abort` port to the `i2c_ctrl_txn_layer` entity which will react to a pulse of that signal. In practice this means if the controller is writing it will send a STOP instead of the next bit. When reading, the controller will finish reading the byte, NACK, and then send a STOP.
> I2C controller: add ability to abort transactions

- hdl/projects/sidecar/qsfp_x32/QSFPModule/QsfpModuleController.bsv
- hdl/projects/sidecar/qsfp_x32/QSFPModule/QsfpModulesTop.bsv
- hdl/projects/sidecar/qsfp_x32/QSFPModule/qsfp_modules_top.rdl
- hdl/projects/sidecar/qsfp_x32/QSFPModule/test/QsfpModuleControllerTests.bsv
- hdl/projects/sidecar/qsfp_x32/QsfpX32ControllerSpiServer.bsv
The current state of upstack software understanding module power control is confusing. The actual hardware power control had an additional level of gating the FPGA that enforced a module being present before turning power on. However, when software comes by to read the `POWER_ENx` registers it sees the modules as being enabled. This is confusing!
This PR splits out the software control of the power enable into a separate `SW_POWER_ENx` registers from the true pin-level hardware state (post-gating) shown in the `POWER_ENx` registers.
The software impact of this changes are minimal. When fetching state the `POWER_ENx` register will represent the what a user would expect. When modifying if a power _should_ be enabled or not, the `SW_POWER_ENx` registers will need to be hit instead.
fixes …
> QSFP Controller: make power control and readback separate

- tools/yosys.bzl
- tools/yosys_gen/templates/synth_py.jinja2
The yosys toolchain was mostly slapped together as proof of concept. After using it in anger for a bit I've found some missing functionality around the logs we're exposing so this exposes more of the correct logs, like we'd like to get warnings from the ghdl synthesizer, the yosys log and the next pnr log with area and timing.
The ghdl thing is a bit strange in that it logs warnings to stderr when run as a plugin in yosys but the warnings don't make it into the log file, probably due to how yosys is logging things. I've captured the stderr there and written it to a file, and printed it to stderr so that when we get a non-zero exit you see the errors in the terminal.
> Improve logging for the yosys toolchain

- hdl/ip/vhd/axi_blocks/BUCK
- hdl/ip/vhd/axi_blocks/axil_interconnect.vhd
- hdl/ip/vhd/axi_blocks/axil_interconnect_2k8.vhd
- hdl/ip/vhd/axi_blocks/axilite_if_2k19_pkg.vhd
- hdl/ip/vhd/axi_blocks/axilite_if_2k8_pkg.vhd
- hdl/ip/vhd/espi/BUCK
- hdl/ip/vhd/espi/sims/espi_th.vhd
- hdl/ip/vhd/fmc_if/BUCK
- hdl/ip/vhd/info/BUCK
- hdl/ip/vhd/spi_nor_controller/BUCK
- hdl/projects/grapefruit/BUCK
This moves the logic for our naive axi-lite fabric block down into a VHDL 2k8-compatible block and then adds a wrapper with the extant interface.  Doing this required adjusting the package names a bit so we could split the 2k19 and 2k9 code so you see the cascading changes in existing IP that pulled in 2k19-compatible packages.
> Axi 2k8 work and cleanup

- hdl/ip/vhd/spi/axi_controller/spi_axi_pkg.vhd
- hdl/ip/vhd/spi/axi_controller/spi_to_axi.vhd
a process doesn't re-init the variables on every call (duh). Yosys complained about comb loops for the vaules that had to hold thier state, we shouldn't do this.  Added back in the assert since we have figured out how to make ghdl drop them with the no-formal flag.
> Bug-fix inferred loop/latch here. Variables only init at the *start*

- tools/vivado.bzl
- tools/yosys.bzl
- tools/yosys_gen/templates/synth_py.jinja2
If a design had multiple blocks that depend on the same core component that also happened to have an RDL provider, when trying to generate the maps at the end of the build we'd get failures b/c we just loop on the RDLproviders and expected an output for each. That's fine, but when there were multiple of the same provider, we'd try to re-declare outputs and get errors from buck2.  We take the list of files and turn it into a set() which drops any duplicates before we loop them to generate our outputs. We only want one copy of each anyway, so this is perfect.
> Unique maps. When one or more blocks depend on the something with an RDL provider, we only want unique copies

- .github/workflows/build.yml
- BUILD.vars.gha
- hdl/projects/psc/BUILD
- hdl/projects/sidecar/ignition_target/BUILD
We need some fixes in ghdl for more modern vhdl files such as https://github.com/ghdl/ghdl/issues/2682
I've installed the new toolchain, we'll see how ci goes.  We can walk this back as the old toolchain is still present on the build machine.
> Bump oss-cad-suite toolchain

- hdl/ip/vhd/i2c/controller/link_layer/i2c_ctrl_link_layer.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_th.vhd
- hdl/ip/vhd/vunit_components/i2c_controller/i2c_ctrlr_vc.vhd
- hdl/projects/cosmo_seq/spd_proxy/BUCK
- hdl/projects/cosmo_seq/spd_proxy/sims/spd_proxy_top_tb.gtkw
- hdl/projects/cosmo_seq/spd_proxy/sims/spd_proxy_top_tb.vhd
- hdl/projects/cosmo_seq/spd_proxy/sims/spd_proxy_top_tb_pkg.vhd
- hdl/projects/cosmo_seq/spd_proxy/sims/spd_proxy_top_th.vhd
- hdl/projects/cosmo_seq/spd_proxy/spd_proxy_top.vhd
This commit adds the `spd_proxy_top` block whose intention is to house an I2C controller which will attempt to utilize the DIMM bus while a CPU is not using it. When the CPU begins using the bus the internal controller will wrap up what it is doing as quickly as possible and we will attempt to gracefully hand the bus over the CPU in a way that doesn't cause problems.
> Add an SPD proxy mux

- tools/fpga_releaser/archive_parser.py
- tools/fpga_releaser/cli.py
- tools/fpga_releaser/config.toml
- tools/fpga_releaser/project.py
after using it in anger, 
- fix up some extraneous prints
- Allow fetching from local buck-out (and filter to selected project paths)
- Fix up hubris paths as decided with matt
> Some cleanup on the fpga releaser

- hdl/ip/vhd/espi/BUCK
- hdl/ip/vhd/espi/sys_regs/espi_regs.rdl
- hdl/ip/vhd/i2c/controller/BUCK
- hdl/ip/vhd/i2c/io_expanders/PCA9506ish/BUCK
- hdl/ip/vhd/i2c/muxes/PCA9545ish/BUCK
- hdl/ip/vhd/i2c/muxes/PCA9545ish/emulated_pca9545_regs.rdl
- hdl/ip/vhd/i2c/muxes/PCA9545ish/pca9545ish_function.vhd
- hdl/ip/vhd/info/BUCK
- hdl/ip/vhd/spi_nor_controller/BUCK
- hdl/ip/vhd/spi_nor_controller/spi_nor_regs.rdl
- hdl/projects/grapefruit/BUCK
- hdl/projects/grapefruit/base_regs/gfruit_regs.rdl
- hdl/projects/grapefruit/base_regs/registers.vhd
- hdl/projects/grapefruit/gfruit_top.rdl
- hdl/projects/grapefruit/sgpio/gfruit_sgpio.vhd
- hdl/projects/grapefruit/sgpio/gfruit_sgpio_regs.rdl
- hdl/projects/grapefruit/sgpio/sgpio_regs.vhd
- tools/rdl.bzl
- tools/site_cobble/rdl_pkg/json_dump.py
Working with @mkeeter we're adding some improvements to the RDL generation and I've made some naming convention enforcement to help facilitate programatic consumption of the generated artifacts.
New Features:
- added "orig_type_name" to top level addrmap json so that the instance name can be linked with the actual hardware generated .json. Remember, we may have multiple copies of the same "hw" with different instance names.
- added "addr_span_bytes" to the top level addrmap json to give a hint to sw tool generation how many registers we have specified. Note that there's a missing feature from SystemRDL spec that would allow reserving undefined register space, so we're stuck telling sizes that are based only on what we've defined. From a hw implementation perspective, it's certainly safe …
> RDL naming convention enforcement and updates

- tools/multitool/multitool_cli.py
- tools/vhdl-ls.bxl
Was getting annoyed at the number of errors reported in vscode since we were pulling in too many of the VUnit and OSVVM files and there were conflicts.  This cleans that up a bit and sets the is_third_party on these files to hide lints also.
> Fix up lsp generation to set 3rd party on osvvm and vunit.

- hdl/ip/vhd/vunit_components/i2c_controller/i2c_ctrlr_vc.vhd
Without this we will miss a rising edge whenever the controller has to ACK (e.g., during a read from a target).
> fix I2C controller VC to drive SCL low during ACK transmit

- hdl/ip/vhd/i2c/controller/link_layer/i2c_ctrl_link_layer.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/i2c_ctrl_txn_layer.vhd
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_tb.gtkw
- hdl/ip/vhd/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_th.vhd
- hdl/ip/vhd/vunit_components/i2c_target/i2c_target_vc.vhd
As discussed, the controller logic will now operate as a push-pull driver. This gives flexibility since if that is desired it will be the default, and adapting a push-pull driver to be open-drain is simple when accompanying tristate logic is still present.
This change also changes the target VC to utilize the `*_int` signals for rising/falling edge triggers since those are adapted to '0' or '1' from the std_logic inout pins.
> make I2C controller push-pull

- hdl/ip/vhd/axi_blocks/BUCK
- hdl/ip/vhd/axi_blocks/axil_target_txn.vhd
- hdl/ip/vhd/espi/BUCK
- hdl/ip/vhd/espi/sys_regs/espi_regs.vhd
- hdl/ip/vhd/fmc_if/BUCK
- hdl/ip/vhd/info/BUCK
- hdl/ip/vhd/info/info_2k8.vhd
- hdl/ip/vhd/spi_nor_controller/BUCK
- hdl/ip/vhd/spi_nor_controller/spi_nor_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sp_i2c_subsystem/BUCK
- hdl/projects/cosmo_seq/sp_i2c_subsystem/sp_i2c_subsystem.vhd
- hdl/projects/cosmo_seq/sp_i2c_subsystem/sp_i2c_subsystem_regs.vhd
- hdl/projects/grapefruit/BUCK
- hdl/projects/grapefruit/base_regs/registers.vhd
- hdl/projects/grapefruit/sgpio/sgpio_regs.vhd
This allows us to share the logic that was currently duplicated in every axi target block.  We were startign to have too much copied code in every axi target block and any future fixing or maintenance was going to get out of hand quickly.
Additionally I slightly re-structured the BUCK files so that rather than importing a package, we import more stuff when bringing in axi-lite stuff so the downstream blocks have fewer common axi-lite parts to manage.
> Refactor axi lite transactions blocks into a common entity

- hdl/projects/cosmo_seq/spd_proxy/BUCK
- hdl/projects/cosmo_seq/spd_proxy/sda_arbiter/sda_arbiter.vhd
- hdl/projects/cosmo_seq/spd_proxy/sda_arbiter/sims/sda_arbiter_tb.gtkw
- hdl/projects/cosmo_seq/spd_proxy/sda_arbiter/sims/sda_arbiter_tb.vhd
This could be parameterized further to be a more general way to arbitrate a shared bus where the FPGA is a proxy, but for now this is what it is.
> make SDA aribtration logic its own module

- hdl/projects/minibar/minibar_controller.rdl
I previously had it smack dab in the middle of a range we expect for an identifying data structure in hubris (https://github.com/oxidecomputer/hubris/blob/a31b6acf6900c04978302b5a1dcc017e9b35e1fc/drv/fpga-api/src/lib.rs#L269)
> minibar: move HCV register to after the ident fields

- hdl/ip/vhd/i2c/io_expanders/PCA9506ish/pca9506_regs.vhd
- hdl/ip/vhd/i2c/io_expanders/PCA9506ish/pca9506_top.vhd
- hdl/projects/cosmo_seq/sp5_hotplug_subsystem/BUCK
- hdl/projects/cosmo_seq/sp5_hotplug_subsystem/perst_oneshot.vhd
- hdl/projects/cosmo_seq/sp5_hotplug_subsystem/sp5_hotplug_subsystem.vhd
Adds some missing functionality for perst_l oneshots and resetting of pca9506 devices when not in a0 for a hopefully final pre-bringup submission here.
This finishes a couple of the remaining issues in #305
> pre-bringup cosmo tasks

- hdl/projects/gimlet/sequencer/GimletRegs.bsv
- hdl/projects/gimlet/sequencer/GimletTopIOSync.bsv
- hdl/projects/gimlet/sequencer/gimlet_seq_fpga_regs.rdl
> gimlet sequencer: add sw control for PCIe clk, disable by default

- hdl/ip/vhd/common/utils/calc_pkg.vhd
- hdl/ip/vhd/memories/BUCK
- hdl/ip/vhd/memories/mixed_width_simple_dpr.vhd
- hdl/ip/vhd/memories/sims/memories_sim_pkg.vhd
- hdl/ip/vhd/memories/sims/memories_tb.vhd
- hdl/ip/vhd/memories/sims/memories_th.vhd
I have a use-case that wants byte-enables on a dual-port ram so I'm adding them and an associated testcase here.
@Aaron-Hartwig: Ready to review
> Add byte-enables to DPR

- hdl/ip/vhd/8b10b/BUCK
- hdl/ip/vhd/8b10b/decode_8b10b.vhd
- hdl/ip/vhd/8b10b/encode_8b10b.vhd
- hdl/ip/vhd/8b10b/helper_8b10b_pkg.vhd
based on chuck benz verilog example.
Added some helper functions which are expected to be useful for ignition simulations where this will be properly exercised, but this unit felt stand-alone enough to be it's own foundational PR.
Rather than build out a bunch of simulations for these blocks  (which are effectively just math functions) I'd  rather focus on integrating this stuff into a more useful ignition simulation and use those test  vehicles to be the ongoing tests of these modules.
> Add 8b10b encoders/decoders 

- hdl/ip/vhd/common/utils/calc_pkg.vhd
- hdl/ip/vhd/crc/BUCK
- hdl/ip/vhd/crc/crc8astar_8wide.vhd
- hdl/ip/vhd/crc/crc8autostar_8wide.vhd
- tools/yosys.bzl
A couple  more mathy blocks that felt separate enough to PR to help prevent massive walls of PRs for ignition. This stuff will all eventually be integrated into ignition and tested there.
A minor update to the yosys/pnr BUCK interface to allow passing in arguments so that I can do sizing builds in yosys + friends w/o needing full pinout constraints. This is useful for testing synth designs to understand logic utilization.
> Add crc8astar and some utility functions used by ignition

- hdl/projects/cosmo_seq/cosmo_seq_top.vhd
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.rdl
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
Wire out control of flash mux and the ignition creset into the sequencer block for board functional verification.
> Add control of ignition flash and creset to sequencer

- hdl/ip/vhd/8b10b/BUCK
- hdl/ip/vhd/8b10b/helper_8b10b_pkg.vhd
Due to how the 8b10b algo works, most tables show the input (8b) in octal or hex with MSB 1st (HGF EDCBA) but show the encoded 10b version in LSB1st (abcdei fghj). Flipping the bit-order in the constants makes it more difficult to compare to tables for correctness, so I have left things in the encoded order, but changed the names and added comments to reflect that and then reversed the bit order before it's consumed.
Problems like this are extremely annoying to notice/debug so it's best to give ourselves the easiest time possible.
This also adds a helper function that will figure out control or non-control character encoding.
> Fix helper function encoded bit order

- hdl/projects/cosmo_seq/BUCK
- hdl/projects/cosmo_seq/cosmo_seq_top.rdl
- hdl/projects/cosmo_seq/cosmo_seq_top.vhd
- hdl/projects/cosmo_seq/debug_module/BUCK
- hdl/projects/cosmo_seq/debug_module/debug_module_top.vhd
- hdl/projects/cosmo_seq/debug_module/debug_regs.rdl
- hdl/projects/cosmo_seq/sp5_uart_subsystem/sp5_uart_subsystem.vhd
Previously, we defaulted to shoving the SP5 uart data out the debug header. That presented challenges with the mfg stations where a uart dongle isn't necessarily connected leading to a wedge due to hardware-handshake.  This makes the default the  SP which will keep the buffer clear (like it does on gimlet) and we have a new memory mapped peripheral to flip the mux back to the debug headers if we need it.
This lays the groundwork for additional debug control of various things which we may want eventually also.
I booted this on my cosmo, and once booted I could use the `humility console-proxy attach` command to get proper uart coms. This verified that we don't wedge during boot and the the sp-console-proxy is working as expected.
> Make SP-console the default UART

- hdl/projects/cosmo_seq/cosmo_seq_top.rdl
- hdl/projects/cosmo_seq/dimms_subsystem/regs/dimm_regs.rdl
No functional changes here. The primary thing is aligning the `addrmap` name and the `.rdl` file name for our codegen over in hubris. Otherwise there's some noise of me rearranging registers into more logical blocks.
> cosmo_seq: cleanup dimm_regs for hubris

- hdl/ip/vhd/espi/sys_regs/espi_regs.rdl
- hdl/ip/vhd/espi/sys_regs/espi_regs.vhd
As requested by Robert, `post_code_count` increments whenever a valid post code is seen. In addition to the primary reset, it can be reset via `espi_reset`. The motivation behind adding this is as an easy way to see "liveliness" of the eSPI bus.
> espi_regs: add a post_code_count register

- hdl/ip/vhd/uart/fifo_uart/axi_fifo_st_uart.vhd
- hdl/projects/cosmo_seq/cosmo_seq_top.vhd
- hdl/projects/cosmo_seq/debug_module/BUCK
- hdl/projects/cosmo_seq/debug_module/debug_module_top.vhd
- hdl/projects/cosmo_seq/debug_module/debug_regs.rdl
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.rdl
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
- hdl/projects/cosmo_seq/sp5_hotplug_subsystem/sp5_hotplug_subsystem.vhd
- hdl/projects/cosmo_seq/sp5_uart_subsystem/BUCK
- hdl/projects/cosmo_seq/sp5_uart_subsystem/sp5_uart_subsystem.vhd
- hdl/projects/cosmo_seq/sp5_uart_subsystem/sp5_uart_subsystem_pkg.vhd
We're going to let lab images enable this in an upcoming PR so minibar nics will work but we don't transmit the pcie clock out the back any time a sidecar is connected.
This also includes previously un-merged UART debug that doesn't really  affect anything functionally but is there for getting some more info out of the box for the host os team.
> add register to allow hubris to control whether we emit backplane PCIE clock when something is connected.

- hdl/ip/vhd/i2c/muxes/PCA9545ish/pca9545ish_function.vhd
- hdl/ip/vhd/i2c/muxes/PCA9545ish/pca9545ish_top.vhd
- hdl/ip/vhd/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_tb.vhd
- hdl/ip/vhd/vunit_components/i2c_controller/i2c_ctrlr_vc.vhd
previously i2c mux actions were taken immediately on the write. In a properly working system, this is a don't care usually but probably not correct. And definitely in a system where the segment we're turning on is already unhappy this breaks the saleae decode and makes debugging harder.
All of the silicon i2c muxes I can find, including the 9545 state something along the lines of:
> When a channel is selected, the channel will become active after a STOP condition has
> been placed on the I2C-bus. This ensures that all SCx/SDx lines are in a HIGH state
> when the channel is made active, so that no false conditions are generated at the time of
> connection.
So we fix that here, and adjust the simulations to wait for the transaction to completely finish before enabling the selected channel. …
> wait until i2c stop to update mux

- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
I noticed that that `humility dashboard` is never showing us in `A0PlusHP`.  It looks like the NIC API status register never changes:
```
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x0 } }
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x0 } }
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x0 } }
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x2 } }
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x2 } }
nic_api_status: NicApiStatusDebug { nic_sm: Ok(Idle) }, nic_raw_status: NicRawStatusDebug { hw_sm: 0x3 } }
nic_api_status: …
```
> Wire up NIC API status

- hdl/ip/vhd/crc/crc8autostar_8wide.vhd
Due to ?? reasons my initial implementation of this was wrong, I assume due to either a column-mode copy-paste error or some other editing mistake.
Since only one factor was messed up, the crc worked fine for some data patterns and generated incorrect data for others.
> Fix typo in crc implementation that was breaking ignition

- hdl/projects/cosmo_seq/cosmo_seq_top.vhd
- hdl/projects/cosmo_seq/sequencer/nic_seq.vhd
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
This adds sequencer irq wired all the way out to the pins for  hubris consumption, and fixes the A0PlusHP state to only be active when the NIC is finally commanded out of reset by the SP5.
Fixes #399 
Fixes #398
> Add sequencer irq pin and fix nic state reporting

- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
We got it into the register interface and then from the sequencer to the pin, but didn't tie the register to the pin in the sequencer itself.
> cosmo-seq: fix missing wire for sequencer IRQ

- hdl/projects/cosmo_seq/cosmo_seq_top.vhd
- hdl/projects/cosmo_seq/sequencer/seq_sync.vhd
- hdl/projects/cosmo_seq/sequencer/sequencer_io_pkg.vhd
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.rdl
- hdl/projects/cosmo_seq/sequencer/sequencer_regs.vhd
- hdl/projects/cosmo_seq/sequencer/sims/sp5_seq_sim_th.vhd
- hdl/projects/cosmo_seq/sequencer/sp5_sequencer.vhd
We bring a bunch of alert signals from on-board sm/pmbus regulators into the interrupt block on cosmo so hubris can choose to get real interrupts (or poll the live status) on these.
We also turn them to be active high in the IFR register since that matches other interrupt sources.
> pmbus sequencer alerts

- hdl/projects/gimlet/sequencer/A0Block.bsv
- hdl/projects/gimlet/sequencer/BUILD
- hdl/projects/gimlet/sequencer/GimletRegs.bsv
- hdl/projects/gimlet/sequencer/gimlet_seq_fpga_regs.rdl
This commit re-purposes the `sp3_to_seq_fsr_req_l` input to drive two different counters in the sequencer. The "edge" counter will count how many times that pin is observed to change value. The "cycle" counter will count how many clock cycles have elapsed since the last change in value, therefore resetting to zero when an edge is observed. Both of these counters are 32-bits wide and will roll over.
fixes #415
> Add registers for GPIO toggle debug
